# permissions for end users to edit mines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mine-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: child-operator
    app.kubernetes.io/part-of: child-operator
    app.kubernetes.io/managed-by: kustomize
  name: mine-editor-role
rules:
- apiGroups:
  - sample.my.domain
  resources:
  - mines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sample.my.domain
  resources:
  - mines/status
  verbs:
  - get
